#!/bin/sh

UID=$(id -u)

docker run ${OPTS:-} --rm \
  -v $PWD/bin:/home/openwrt/bin \
  -v $PWD/build_dir:/home/openwrt/build_dir \
  openwrt sh -xc \
    "usermod -u $UID openwrt && \
     chown openwrt -R bin/ build_dir/ tmp/ staging_dir/ && \
     exec sudo -u openwrt -- $@"
