version: 2
jobs:
  all:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache: &cache_restore
          keys:
            - v1-{{ .Branch }}-{{ .Revision }}
            - v1-{{ .Branch }}
            - v1-
          paths:
            - /caches/app.tar

      - run:
          name: build-builder
          command: |
            docker build -t openwrt .
            docker -v $PWD/bin:/home/openwrt/bin run openwrt

      - store_artifacts:
          path: $PWD/bin

      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app

workflows:
  version: 2
  all:
    jobs:
      - all
